---
- name: stop vm
  block:
    - name: wait for server to stop responding
      ansible.builtin.wait_for:
        host: "{{ template_vm_ip_address }}"
        port: "{{ vm_ansible_port | default('5986') }}"
        timeout: 120
        state: stopped
      failed_when: false

    - name: wait for vm to power off (pre 2.9)
      ansible.builtin.include_tasks: wait_vm_poweredoff_pre29.yml
      when: ansible_version.full is version('2.9', '<')

    - name: wait for vm to power off (post 2.9)
      ansible.builtin.include_tasks: wait_vm_poweredoff.yml
      when: ansible_version.full is version('2.9', '>=')

  rescue:
    - name: stop vm
      ovirt.ovirt.ovirt_vm:
        auth: "{{ ovirt_auth }}"
        cluster: "{{ providers.ovirt.cluster }}"
        name: "{{ template.name }}"
        state: stopped
      when: template is defined

    - name: wait for vm to power off (pre 2.9)
      ansible.builtin.include_tasks: wait_vm_poweredoff_pre29.yml
      when: ansible_version.full is version('2.9', '<')

    - name: wait for vm to power off (post 2.9)
      ansible.builtin.include_tasks: wait_vm_poweredoff.yml
      when: ansible_version.full is version('2.9', '>=')

- name: reconfigure vm
  ovirt.ovirt.ovirt_vm:
    auth: "{{ ovirt_auth }}"
    cluster: "{{ providers.ovirt.cluster }}"
    name: "{{ template.name }}"
    boot_devices:
      - hd
    cd_iso: ""
    custom_properties: "{{ custom_properties_efi if (template_vm_efi | bool and custom_efi_enabled | bool) else ([{}]) }}"
    force: true
    state: present
  when: template is defined
